server:
  port: 8080

twelvedata:
  api:
    scheme: https
    host: api.twelvedata.com
    endpoints:
      quote: quote
      marketCap: market_cap
    key: 3b4c1a0bd9de4b5fb77e842e89487c4c

alphavantagedata:
  api:
    scheme: https
    host: alphavantage.co
    endpoints:
      query: query
    function: OVERVIEW
    key: XTXOJTEUX9LM3PFZ

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bc2504
    username: root
    password: admin1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    databasePlatform: org.hibernate.dialect.MySQL8Dialect
  redis:
    host: localhost
    port: 6379
    timeout: 6000
# https://www.alphavantage.co/query?function=OVERVIEW&symbol=GOOG&apikey=XTXOJTEUX9LM3PFZ
# XTXOJTEUX9LM3PFZ